---
# tasks file for zabbix-proxy
- name: Install MySQL 8.0
  dnf:
    name: "{{ mysql_packages }}"
    state: present

- name: Start and Enable MySQL Server 8.0
  service:
    name: mysqld
    state: started
    enabled: true

- name: Instalando o repositório do Zabbix
  dnf: 
    name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-2.el8.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: Instalando os pacotes Zabbix
  dnf:
    name: "{{ zabbix_packages }}"

- name: Set root password localhost
  mysql_user:
    name: "{{ mysql_root_user }}"
    host: localhost
    password: "{{ mysql_root_pass }}"
    state: present
    check_implicit_admin: yes
    login_user: "{{ mysql_root_user }}"
    login_host: localhost
    login_password: "{{ mysql_root_pass }}"

- name: Create user of Proxy
  mysql_user:
    login_host: localhost
    login_password: "{{ mysql_root_pass }}"
    login_user: "{{ mysql_root_user }}"
    name: "{{ mysql_zbx_user }}" 
    password: "{{ mysql_zbx_pass }}"
    priv: "{{ mysql_zbx_mdb }}.*:ALL"
    state: present
    host: localhost


#- name: Descompactando Arquivos create.sql.gz
#  command: gunzip /usr/share/doc/zabbix-sql-scripts/mysql/server.sql.gz
#  when: create_sql_gz_exist.stat.exists

#- name: Importando tabelas para o banco de dados do Proxy
#  mysql_db:
#    state: import
#    login_host: localhost
#    login_password: "{{ mysql_zbx_pass }}"
#    login_user: "{{ mysql_zbx_user }}"
#    name: "{{ mysql_zbx_mdb }}"
#    collation: utf8_bin
#    encoding: utf8
#    target: /usr/share/doc/zabbix-sql-scripts/mysql/proxy.sql 
#  when: db_created.changed 

#- name: Copiando o arquivo "zabbix_server.conf" !
#  template: 
#    src: zabbix_server.conf
#    dest: /etc/zabbix/zabbix_server.conf

- name: copy Template zabbix_proxy.conf
  template:
    dest: /etc/zabbix
    src: zabbix_proxy.conf

- name: Start service zabbix-proxy
  service:
      name: zabbix-proxy
      enabled: yes
      state: restarted

...
