---
# tasks file for winsrv-agent
- name: Download Zabbix Agent for Windows
  win_get_url:
    url: https://cdn.zabbix.com/zabbix/binaries/stable/6.0/6.0.4/zabbix_agent-6.0.4-windows-amd64-openssl.msi
    dest: C:\Users\Administrator\Downloads\zabbix_agent.msi

#- name: Restart a service
#  win_service:
#    name: Zabbix Agent
#    state: stopped

- name: Install Zabbix Agent
  win_command: msiexec /i "C:\Users\Administrator\Downloads\zabbix_agent.msi" /qn^ SERVER="{{zbx_srv_addr_01}}"

- name: Copy Template Zabbix Agent
  win_template:
    src: winsrv-agent/templates/zabbix_agent2.conf
    dest: 'C:\Program Files\Zabbix Agent\zabbix_agent2.conf'

- name: Restart a service
  win_service:
    name: Zabbix Agent
    state: restarted





