---
- name: Install MySQL Server 8.0
  dnf:
    name: "{{ mysql_packages }}"
    state: present

- name: Start and Enable MySQL Server 8.0
  systemd:
    name: mysqld
    state: restarted
    enabled: yes 

#- name: Set root password localhost
#  mysql_user:
#    name: "{{ mysql_root_user }}"
#    host: "{{ mysql_host }}"
#    password: "{{ mysql_root_pass }}"
#    state: present
#    check_implicit_admin: yes
#    login_user: "{{ mysql_root_user }}"
#    login_host: "{{ mysql_host }}"
#    login_password: "{{ mysql_root_pass }}"
#  notify:
#    - Restart MySQL

- name: Instalando o repositório do Zabbix
  dnf:
    name: https://repo.zabbix.com/zabbix/{{ zabbix_release }}/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/zabbix-release-{{ zabbix_version }}.el{{ ansible_distri    bution_major_version }}.noarch.rpm
#    name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: Install packages Zabbix CentOS
  dnf:
    name: "{{ zabbix_packages }}"
    state: latest

#- name: Create database
#  mysql_db:
#    login_host: "{{ mysql_host }}"
#    login_password: "{{ mysql_login_password }}"
#    login_user: "{{ mysql_login_user }}"
#    name: "{{ mysql_database }}"
#    encoding: utf8
#    collation: utf8_bin
#  register: db_created

#- mysql_user:
#    login_host: "{{ DBHost_address }}"
#    login_password: "{{ login_mysql_password }}"
#    login_user: "{{ login_mysql_user }}"
#    name: "{{ DBUser }}"
#    password: "{{ DBPassword }}"
#    priv: '.:ALL'
#    state: present
#    host: "{{ item }}"
#  with_items:
#    - "{{ zabbix_server_address }}"
#    - "{{ zabbix_frontend_address }}"
#    - "{{ DBHost_address }}"


#- name: Removes all anonymous user accounts
#  community.mysql.mysql_user:
#    name: ''
#    host_all: yes
#    state: absent


