---
# Tasks file for mysql-server
# Configurando o Firewalld
#- name: Iniciando e habilitando o Firewalld
#  service:
#    name: firewalld
#    state: started
#    enabled: true

#- name: Configurando as regras do Firewall
#  firewalld:
#    zone: public
#    service: "{{ item }}"
#    permanent: yes
#    state: enabled
#  loop:
#    - mysql

#- name: Restart o serviço Firewalld
#  service:
#    name: firewalld
#    state: restarted

#- name: Instalando o MySQL Server 8.0
#  dnf:
#    name: "{{ mysql_packages }}"
#    state: present

#- name: Iniciar e habilitar o MySQL Server 8.0
#  service:
#    name: mysqld
#    state: started
#    enabled: true 

#- name: Instalando o repositório Zabbix
#  dnf:
#    name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-2.el8.noarch.rpm
#    state: present
#    disable_gpg_check: yes

#- name: Instalando os pacotes Zabbix
#  dnf:
#    name: "{{ zabbix_packages }}"

##- name: Set root password localhost
##  mysql_user:
##    name: "{{ mysql_root_user }}"
##    host: localhost
##    password: "{{ mysql_root_pass }}"
##    state: present
##    check_implicit_admin: yes
##    login_user: "{{ mysql_root_user }}"
##    login_host: localhost
##    login_password: "{{ mysql_root_pass }}"

- name: Criar o banco
  mysql_db:
    login_host: localhost
    login_password: "{{ mysql_root_pass }}"
    login_user: "{{ mysql_root_user }}"
    name: "{{  mysql_zbx_mdb}}"
    encoding: utf8mb4
#    encoding: utf8
    collation: utf8mb4_bin
#    collation: utf8_bin
  register: db_created

# Criando os usuários nos domínios
##- mysql_user:
##    login_host: localhost
##    login_password: "{{ mysql_root_pass }}"
##    login_user: "{{ mysql_root_user }}"
##    name: "{{ mysql_zbx_user }}"
##    password: "{{ mysql_zbx_pass }}"
###    priv: "*.*:ALL,GRANT" 
##    priv: "{{  mysql_zbx_mdb}}.*:ALL" 
##    state: present
##    host: "{{ item }}"
##  with_items:
##    - "{{ zbx_srv_addr_01 }}"
##    - "{{ zbx_srv_addr_02 }}"
##    - "{{ zbx_srv_addr_03 }}"
##    - "{{ zbx_frt_addr }}"
##    - "{{ mysql_host }}"

#- name: Envio do arquivo zbxsrvmdb.sql
#  copy:
#    src: mysql-server/files/zbxsrvmdb.sql
#    dest: /usr/share/doc/zabbix-sql-scripts/mysql/zbxsrvmdb.sql

#- name: Verificar se o arquivo existe
#  stat:
#    path: /usr/share/doc/zabbix-sql-scripts/mysql/zbxsrvmdb.sql.gz
#  register: create_sql_gz_exist

#- name: Descompactando Arquivos create.sql.gz
#  command: gunzip /usr/share/doc/zabbix-sql-scripts/mysql/zbxsrvmdb.sql.gz
#  when: create_sql_gz_exist.stat.exists

#- name: Importando tabelas para o banco de dados do Zabbix
#  mysql_db:
#    state: import
#    login_host: localhost
#    login_password: "{{ mysql_root_pass }}"
#    login_user: "{{ mysql_root_user }}"
#    name: "{{ mysql_zbx_mdb }}"
#    collation: utf8_bin
#    encoding: utf8
#    target: /usr/share/doc/zabbix-sql-scripts/mysql/server.sql
#  when: db_created.changed

- name: Voltando backup do Banco
  shell:
#    cmd: mysql -uroot -p123@Mudar zbxsrvmdb < /usr/share/doc/zabbix-sql-scripts/mysql/Full.zbxsrvmdb.Friday-07-10-22-15h:59m.sql
    cmd: mysql -uroot -p123@Mudar zbxsrvmdb < /usr/share/doc/zabbix-sql-scripts/mysql/Full.zbxsrvmdb.Tuesday-02-08-22-13h-10m.sql
#    cmd: mysql -uroot -p123@Mudar zbxsrvmdb < /usr/share/doc/zabbix-sql-scripts/mysql/server.sql

...
