---
# Iniciando o serviço de Firewall
- name: Iniciando e habilitando o Firewall
  service:
    name: firewalld
    state: started
    enabled: true

- name: Configurando as regras do Firewall
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - zabbix-agent

- name: Restart o serviço Firewalld
  service:
    name: firewalld
    state: restarted

# Firewall Configuration
#- name: Configure Firewall
#    firewalld: zone=public service=http permanent=yes state=enabled

#- name: Stoped the Firewall
#  command: systemctl disable firewalld

#- name: Disabling Firewall
#  systemd:
#    name: firewalld
#    state: disabled
#  command: systemctl disable firewalld

# tasks file for zabbix-agent
- name: Instalando o repositório do Zabbix
  dnf:
#    name: https://repo.zabbix.com/zabbix/{{ zabbix_release }}/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/zabbix-release-{{ zabbix_version }}.el{{ ansible_distri    bution_major_version }}.noarch.rpm

#    name: https://repo.zabbix.com/zabbix/{{ zabbix_release }}/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/zabbix-release-{{ zabbix_version }}.el{{ ansible_distr    i    bution_major_version }}.noarch.rpm
   name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-2.el8.noarch.rpm
   state: present
   disable_gpg_check: yes

- name: Install packages Zabbix CentOS
  dnf:
   name: "{{ zabbix_agent_package }}"
   state: present

- name: Copy template zabbix-agent.conf CentOS
  template:
    src: zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf 

- name: Start service Zabbix Agent
  service: 
    name: zabbix-agent2 
    state: restarted 
    enabled: yes

...
