---
# tasks file for zabbix-server
# Iniciando e habilitando o Firewalld
- name: Iniciando e habilitando o Firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: Configurando as regras do Firewall
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - zabbix-server

- name: Restart o serviço Firewalld
  service:
    name: firewalld
    state: restarted
    
- name: Instalando o repositório do Zabbix
  dnf: 
    name: https://repo.zabbix.com/zabbix/{{ zabbix_release }}/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/zabbix-release-{{ zabbix_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm
#    name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: Install packages Zabbix CentOS
  dnf:
    name: "{{ zabbix_packages }}"
    state: latest

- name: Copiando o arquivo "zabbix_server.conf" !
  template: 
    src: zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf

- name: Start service zabbix-server
  service:
      name: zabbix-server
      enabled: yes
      state: restarted

...
