---
# tasks file for zabbix-front
# Configurando o Firewalld
- name: Iniciando e habilitando o Firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: Configurando as regras do Firewall
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - http
    - https

- name: Reiniciando o serviço do Firewall
  service:
    name: firewalld
    state: restarted
    
# Baixando o repositório Zabbix
- name: Install Zabbix Repository CentOS
  dnf: 
#    name: https://repo.zabbix.com/zabbix/{{ zabbix_release }}/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/zabbix-release-{{ zabbix_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm
    name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-2.el8.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: Install packages Zabbix CentOS
  dnf:
    name: "{{ zabbix_packages }}"
    state: latest

- name: Copy Files zabbix.conf.php
  copy:
    dest: /etc/zabbix/web/zabbix.conf.php
    src: /ansible-roles/ansible-lab/zabbix-front/files/zabbix.conf.php

- name: Start service httpd
  service:
      name: httpd
      enabled: yes
      state: restarted

- name: Start service php-fpm
  service:
      name: php-fpm
      enabled: yes
      state: restarted
...
